meta_product_name: "L.E.A.D"
meta_title: "Leads on Event-Activated Data - Recevez quotidienement des données fiables avec un minimum de ressources"
meta_description: "Optimisez vos chances de conversion auprès de vos prospects juridiques
en les contactant au meilleur moment"
meta_image: "https://res.cloudinary.com/dnpdonlro/image/upload/v1606218201/Legal_srnb3p.jpg" # devrait exister dans `app / assets / images /`
twitter_account: "@product_twitter_account" # requis pour les cartes Twitter
